id: 79
schoolId: 63
token: eyJhbGciOiJSUzI1NiJ9.eyJpZCI6NzksInVzZXJOYW1lIjoi5ZC05a6d54-NX1dVQlo2IiwiZXhwIjoxNjY5MTExNDkyfQ.DcmntlH2XDoxRgCp4ERs3xx8hzS8hydHR-KyWBt8jFiQVy3dBuDmepVlBTmkGX26oAz1pct98U8qWU9s_6gFbt8S0sX7V8KRGe-qDPi4tv2EGqxBzSmKLLNeVCQzuj9Gcs0dclROQOYzrrUQ6uu9LrcBmGKBNk7t2QOGIjLLaJs
